### ISSUE TITLE
google_analytics.ua 수정을 요청합니다.

### ISSUE THREAD

**Issue by johngrib** [Achelous1/achelous1.github.io#16]
안녕하세요. @Achelous1 님의 사이트의 설정에 들어있는 google_analytics.ua 값이 제 계정의 google_analytics.ua 값이라서, 선생님 사이트의 통계가 제 구글 애널리틱스에서 함께 집계되고 있습니다. 저는 이제 GA4로 옮겨갔기 때문에 이 통계가 저에게 불편을 주지는 않습니다. 하지만 @Achelous1 사이트의 통계 정보가 제게 전달되고 있으니 바람직한 상황은 아닙니다. @Achelous1 님의 구글 계정으로 google_analytics 콘솔을 확인하시면 ua 값을 확인하실 수 있을 것입니다. 확인한 값으로 config 파일을 수정하시면 자신의 계정에서 통계를 확인하실 수 있을 것이고, 저에게도 전달되지 않을 거에요.

아래의 이미지는 제 google analytics 콘솔에서 @Achelous1 님의 블로그 통계를 집계한 것입니다.

![image](https://user-images.githubusercontent.com/1855714/168455078-6294f688-4f86-47e9-8822-c9834c4e2238.png)

수정할 파일의 링크는 다음과 같습니다.

https://github.com/Achelous1/achelous1.github.io/blob/main/_config.yml#L55-L56

https://github.com/Achelous1/achelous1.github.io/commit/3e008536f6f4c7f6bb55e68247e5bfd6e1d3017a#diff-ecec67b0e1d7e17a83587c6d27b6baaaa133f42482b07bd3685c77f34b62d883R55

**Comment by Achelous1** [comment]
앗 안녕하세요! 이슈 열어주셔서 감사합니다! 해당 내용 확인하여 반영하도록 하겠습니다!

**Comment by johngrib** [comment]
수정하신 내용 확인했습니다. :-)
https://github.com/Achelous1/achelous1.github.io/commit/567fdfc5e733c4112e140147bf9ebe8df6a80425

**Comment by johngrib** [comment]
다른 사람이 @Achelous1 님의 사이트를 포크해서 정적 사이트를 운영한다면 같은 일이 @Achelous1 님께도 일어날 수 있습니다. 이런 일을 예방하려면 README.md 등에서 GA 아이디 수정을 권고하거나, skeleton 사이트 포크를 권장하는 것을 생각할 수 있습니다.

좋은 하루 보내세요.

**Comment by Achelous1** [comment]
넵 만약 상위와 같은 상황 발생한다면 권고드리도록 하겠습니다! 다시한번 감사드립니다!
